/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "matrixOp.h"

bool_t
xdr_matrix (XDR *xdrs, matrix *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->rows))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->cols))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, MAX_MATRIX_ELEMENTS,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrix_pair (XDR *xdrs, matrix_pair *objp)
{
	register int32_t *buf;

	 if (!xdr_matrix (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_matrix (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrix_result (XDR *xdrs, matrix_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_matrix (xdrs, &objp->value))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, ERROR_MESSAGE_LEN))
		 return FALSE;
	return TRUE;
}
