/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "matrixOp.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

matrix_result *
matrix_add_1(matrix_pair *argp, CLIENT *clnt)
{
	static matrix_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MATRIX_ADD,
		(xdrproc_t) xdr_matrix_pair, (caddr_t) argp,
		(xdrproc_t) xdr_matrix_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matrix_result *
matrix_multiply_1(matrix_pair *argp, CLIENT *clnt)
{
	static matrix_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MATRIX_MULTIPLY,
		(xdrproc_t) xdr_matrix_pair, (caddr_t) argp,
		(xdrproc_t) xdr_matrix_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matrix_result *
matrix_transpose_1(matrix *argp, CLIENT *clnt)
{
	static matrix_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MATRIX_TRANSPOSE,
		(xdrproc_t) xdr_matrix, (caddr_t) argp,
		(xdrproc_t) xdr_matrix_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matrix_result *
matrix_inverse_1(matrix *argp, CLIENT *clnt)
{
	static matrix_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MATRIX_INVERSE,
		(xdrproc_t) xdr_matrix, (caddr_t) argp,
		(xdrproc_t) xdr_matrix_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
